modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Fring-BS/Eating-Animation-Fork/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/Fring-BS/Eating-Animation-Fork"
logoFile="assets/eatinganimationid/eatinganimationicon.png"
credits="Original mod by theone_ss (MIT License)"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
